---
title: "NSCH 2024 - Parents Reporting Job Changes Due to Child Care Problems"
author: Carter Nesmith
date: July 6, 2026
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Required Packages

```{r load-packages}
library(haven)
library(dplyr)
library(survey)
library(tidyr)
```

## Read Data

Read the 2024 NSCH topical file.

```{r read-data}
nsch <- read_dta(
  "C:/Users/cnesmith/OneDrive - Center For American Progress/Desktop/Data Dashboard/Number of parents reporting job changes due to problems with child care/nsch_2024e_topical.dta"
)
```

## Prepare Variables

Convert variable names to lowercase.

```{r lowercase-names}
names(nsch) <- tolower(names(nsch))
```

Rename variable and create grouped strata.

```{r rename-and-stratify}
nsch <- nsch %>%
  rename(jobchange = k6q27) %>%
  mutate(
    stratumgroup = interaction(fipsst, stratum, drop = TRUE)
  )
```

## Define Survey Design

```{r survey-design}
design <- svydesign(
  ids = ~hhid,
  strata = ~stratumgroup,
  weights = ~fwc,
  data = nsch,
  nest = TRUE
)
```

## Create Weighted Counts

```{r weighted-counts}
jobchange_table <- as.data.frame(
  svytable(~fipsst + jobchange, design)
)
```

## State Lookup Table

```{r state-lookup}
state_lookup <- data.frame(
  fipsst = c(1,2,4,5,6,8,9,10,11,12,13,15,16,17,18,19,20,21,22,23,
             24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,
             42,44,45,46,47,48,49,50,51,53,54,55,56),
  state = c(
    "Alabama","Alaska","Arizona","Arkansas","California","Colorado",
    "Connecticut","Delaware","District of Columbia","Florida",
    "Georgia","Hawaii","Idaho","Illinois","Indiana","Iowa",
    "Kansas","Kentucky","Louisiana","Maine","Maryland",
    "Massachusetts","Michigan","Minnesota","Mississippi",
    "Missouri","Montana","Nebraska","Nevada","New Hampshire",
    "New Jersey","New Mexico","New York","North Carolina",
    "North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania",
    "Rhode Island","South Carolina","South Dakota","Tennessee",
    "Texas","Utah","Vermont","Virginia","Washington",
    "West Virginia","Wisconsin","Wyoming"
  )
)
```

## Convert Factor Variables and Add Labels

```{r convert-and-label}
jobchange_table <- jobchange_table %>%
  mutate(
    fipsst = as.numeric(as.character(fipsst)),
    jobchange = as.character(jobchange)
  ) %>%
  left_join(state_lookup, by = "fipsst") %>%
  mutate(
    jobchange = recode(
      jobchange,
      "1" = "Yes",
      "2" = "No"
    )
  )
```

## Create Wide Table

```{r wide-table}
jobchange_table_wide <- jobchange_table %>%
  select(state, jobchange, Freq) %>%
  pivot_wider(
    names_from = jobchange,
    values_from = Freq
  ) %>%
  arrange(state)
```

## View Table

```{r view-table}
jobchange_table_wide
```
